[package]
name = "rjsyn"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
anyhow = "1"
indexmap = "2"
smallvec = "1"

[dev-dependencies]
insta = { version = "1", features = ["yaml"] }
